### ISSUE TITLE
The legal status of devkitARM's various crt0 files is unclear

### ISSUE THREAD

**Issue by ketsuban** [devkitPro/buildscripts#31]
Pursuant to a heated conversation on an otherwise unrelated pull request elsewhere.

The files in this repository under `dkarm-eabi/crtls` are included in devkitARM but have no license attached; as such, they assume the licensing conditions of the repository (none). For most of them, this is a curiosity since they never leave devkitARM, but it creates a complication in the case of the various `crt0.s` files. Since these are linked into the work of anyone who compiles something with devkitARM, they need to be licensed such that it's legal to do that.

As I see it the solution is to clearly label these files with a license condition (presumably the same GPL-with-linking-exception license as libgcc) so as to be crystal clear that there's no legal trouble in using them.

**Comment by aaaaaa123456789** [comment]
I'll point out that the GPL violation claimed in that issue is unrelated to crt0, and instead refers to this text (starting at line 17 on build-devkit.sh):

>Please note, these scripts are provided as a courtesy, toolchains built with them are for personal use only and may not be distributed by entities other than devkitPro.

This, in our opinion, is a "further restriction" according to section 7 of the GPLv3, and thus an infringement of section 10, third paragraph. It also allows users to delete that restriction, as per section 7 of the GPLv3:

>If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.

(Note that build scripts must necessarily be licensed under the GPL if the whole work is to be so licensed, as required per its definition of "Corresponding Source".)

This is **not** the same as the acceptable additional term, under section 7(e), to require recipients to rename the tool prior to distribution, particularly if it refers to distribution of a modified version.

**Comment by WinterMute** [comment]
Locked due to anonymous trolling, sorry.

We'll get to this soon.

For clarification there is no intent to claim proprietary licenses on the crt0 files & I have no issue with clarifying their status. Like libgcc and the rest of the gcc infrastructure there's an implicit GPLv3 with linking exception with these.

There are other people I need to discuss licensing with and we may end up explicitly using MIT or something similar for these files.
