### ISSUE TITLE
buildscripts fail (404) requesting these files from download.devkitpro.org

### ISSUE THREAD

**Issue by concussious** [devkitPro/buildscripts#57]
Buildscripts for devkitPPC r43 fail on FreeBSD 13.2-RELEASE/amd64 with:

```
devkitppc-rules-1.1.2.tar.gz                                                         
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current      
                                 Dload  Upload   Total   Spent    Left  Speed        
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0       
curl: (22) The requested URL returned error: 404                                     
Error: Failed to download devkitppc-rules-1.1.2.tar.gz   
```

Filed here because:
* the buildscripts repo does not have issues open
* these appear to be the files the build-devkit.sh is looking for

I cannot use pacman because I am using FreeBSD.
I can, however, maintain or pass upstream a port when I get it working.
GCC and all other dependencies listed on the buildscripts readme are already packaged and working on FreeBSD.

**Comment by WinterMute** [comment]
The best way to obtain the ancillary files and indeed the rest of the libraries we supply is via pacman - the devkitPPC package doesn't contain devkitppc-rules but rather has it as a dependency. [devkitPro-pacman](https://github.com/devkitPro/pacman) should really be buildable as is on FreeBSD. Pacman won't replace your system package manager, we use it simply to maintain the packages we distribute within /opt/devkitpro (some 276 packages in all).

If you're willing to help sort out building pacman for FreeBSD we can sort out toolchain packages fairly easily.

**Comment by concussious** [comment]
Please excuse the churn, dropped my phone.

**Comment by nekobbbbbbit** [comment]
I too am building on FreeBSD. I can use pacman, mostly just for the libraries so I don't have to build all the things from scratch. Unfortunately, I do need to build the toolchains myself.

@WinterMute: You should really move away from self hosting these kind of things. For one, it technically adds a little layer of concern, for example: what if the downloads server got hacked? Of course for pacman this isn't a biggy, but for these archives it is since there isn't any protection in place. Also all the issues here are just 404's, just point to the binaries themselves, those are generally designed to always be up (as least stay up longer than your packages tend to)

**Comment by WinterMute** [comment]
These files aren't missing

```davem@dkbuilder:~$ wget downloads.devkitpro.org/devkitppc-rules-1.1.2.tar.gz 
--2023-10-29 09:38:01--  http://downloads.devkitpro.org/devkitppc-rules-1.1.2.tar.gz
Resolving downloads.devkitpro.org (downloads.devkitpro.org)... 104.21.2.51, 172.67.128.184, 2606:4700:3033::ac43:80b8, ...
Connecting to downloads.devkitpro.org (downloads.devkitpro.org)|104.21.2.51|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.devkitpro.org/devkitppc-rules-1.1.2.tar.gz [following]
--2023-10-29 09:38:01--  https://downloads.devkitpro.org/devkitppc-rules-1.1.2.tar.gz
Connecting to downloads.devkitpro.org (downloads.devkitpro.org)|104.21.2.51|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/devkitpro/devkitppc-rules/archive/refs/tags/v1.1.2.tar.gz [following]
--2023-10-29 09:38:01--  https://github.com/devkitpro/devkitppc-rules/archive/refs/tags/v1.1.2.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/devkitPro/devkitppc-rules/tar.gz/refs/tags/v1.1.2 [following]
--2023-10-29 09:38:01--  https://codeload.github.com/devkitPro/devkitppc-rules/tar.gz/refs/tags/v1.1.2
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1717 (1.7K) [application/x-gzip]
Saving to: ‘devkitppc-rules-1.1.2.tar.gz’

devkitppc-rules-1.1.2.tar.gz            100%[=============================================================================>]   1.68K  --.-KB/s    in 0s      

2023-10-29 09:38:02 (4.28 MB/s) - ‘devkitppc-rules-1.1.2.tar.gz’ saved [1717/1717]```

**Comment by WinterMute** [comment]
@nekobbbbbbit Clearly 404s on latest sources are because we haven't uploaded them yet. 

All the packages are signed and pacman checks these signatures.

We discourage people from building manually and providing anything that "does the magic on their own" because it results in outdated and/or broken tools which are of course detrimental to our users. There are endless projects out there with instructions to install old toolchains and libraries over the top of existing installations which ultimately results in people not being able to build anything at all. We hear about this eventually but often the users affected don't have the experience to understand why everything is broken and blame us.

Your cynicism is misdirected.

**Comment by nekobbbbbbit** [comment]
@WinterMute I was quite tired last night, I apologize for the cynicism, i probably sounded a bit schizophrenic. But anywhom, you didn't dispute my claims here properly

> These files aren't missing

That packages missing for me were a binutils, *using* the latest release of this buildscripts

> All the packages are signed and pacman checks these signatures.

Not the package here though. I'm not sure whats happening but v41 binutils kept failing to fetch with a 404, even through a web browser.

> because it results in outdated and/or broken tools which are of course detrimental to our users.

Please explain to me how this happens when i just want to build the compiler. Do you think that people who compile manually **aren't** prolific enough to handle any "updates" on their own?

You do realize I can theoretically still use Pacman (which helps me stay up to date on packages) without breaking trust or builds since im only downloading libraries I need, plus while still linking using my compiler that devkit pacman provides?

What is a user to you? I can probably understand that when working in the homebrew dev field you have lots of people who probably couldn't, say, build or relocate a tool chain on their own and just want to make a little game. But at the same time, you *have* a convenient solution for said users, I don't see why you should be against manual buildings

---

Anyway I don't want to slapfight, I have some advice for you maybe to clear this and such cases up:

1. For advice, I would instead word "discouraging" messages about building toolchains to instead say "**FOR EXPERTS ONLY**", or something like that. This is fairly commonly done with these sort of projects. Don't pull people away from building manually, just hint that support isn't provided at all. For systems like *BSD and maybe nicher systems people use for fun, this message should be very clear. (I'd personally love to work with you for providing FreeBSD and OpenBSD packages though, if you'd like)
2. Don't point tar archives to your downloads archive, in fact, *never* do that unless you're certain a package will or is dead. Instead, point to the GNU servers. You're only asking for more 404 issues and possible security issues (these are NOT signed)

**Comment by WinterMute** [comment]
As I said earlier "Clearly 404s on latest sources are because we haven't uploaded them yet."

This issue is reporting problems with devkitppc-rules-1.1.2.tar.gz which aren't missing. It's not appropriate to hijack this issue for other files and other problems you may have with how we distribute our binaries.

> Do you think that people who compile manually aren't prolific enough to handle any "updates" on their own?

We've being doing this for.a while now. We know users who insist on building manually & opening issues here will often cause issues down the line. They all think they're experts. We don't have the time or energy to help them with the 101 issues people encounter while building and while using binaries they've built themselves.

GPL requires we keep our own copies of the source we use.

We aren't interested in spending our time arguing about this. It takes time away from other, more productive things.
